/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

#ifndef CHARLIEPLEXING_H
#define	CHARLIEPLEXING_H

#include "mcc_generated_files/system/system.h"
#include <stdint.h>
#include <stdbool.h>

#define PINS_NUMBER           3
#define LEDS_NUMBER           (PINS_NUMBER * (PINS_NUMBER - 1))

/*--------- DATA TYPES ---------*/
typedef struct {
    PORT_t *port;
    uint8_t mask;
} drive_t;

typedef struct {
    uint8_t anode;
    uint8_t cathode;
} charlie_t;

/*--------- FUNCTION PROTOTYPES ---------*/
void CharlieInit(void);
void CharlieOn(uint8_t);
void CharlieOff(uint8_t);
void CharlieToggle(uint8_t);
void CharlieAll(bool *pData);
void CharlieHandler(void);

#endif	/* CHARLIEPLEXING_H */